In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [2]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=46)
scores = cross_validate(rf, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974022849894872 0.8895541200858814


In [3]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23393839 0.49932932 0.26673229]


In [4]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=46)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8959014816240138


In [5]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=46)
scores = cross_validate(et, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8876295624491005


In [6]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.1906123  0.52503883 0.28434887]


In [7]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state= 46)
scores = cross_validate(gb, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8718505219515806


In [8]:
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2,
    random_state= 46)
scores = cross_validate(gb, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


In [9]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.15847435 0.68011319 0.16141245]


In [10]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=46)
scores = cross_validate(hgb, train_input, train_target,
                        return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

c:\Users\korea\anaconda3\envs\ET_study\Lib\site-packages\sklearn\experimental\enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(


0.9321723946453317 0.8801241948619236


In [11]:
from sklearn.inspection import permutation_importance

hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target,
                                n_repeats=10, random_state=46, n_jobs=-1)
print(result.importances_mean)

[0.08914759 0.23842602 0.08147008]


In [12]:
result = permutation_importance(hgb, test_input, test_target,
                                n_repeats=10, random_state=46, n_jobs=-1)
print(result.importances_mean)

[0.06184615 0.20661538 0.04784615]


In [13]:
hgb.score(test_input, test_target)

0.8723076923076923

In [14]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=46)
scores = cross_validate(xgb, train_input, train_target,
                        return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9555033709953124 0.8799326275264677


In [16]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=46)
scores = cross_validate(lgb, train_input, train_target,
                        return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.935828414851749 0.8801251203079884
