In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 8])
c = np.array([4, 9, 0, 3])

A = np.vstack([a, b, c])

print(A)
print(A.shape)
print(A.dtype)

[[1 2 3 4]
 [4 5 6 8]
 [4 9 0 3]]
(3, 4)
int32


Indexing

In [3]:
print(A[0])
print(A[2])

[1 2 3 4]
[4 9 0 3]


Column Indexing

In [4]:
print(A[:, 0]) # 각 행의 0번째 값들을 가져옴

[1 4 4]


In [5]:
print(A[:, 3]) # 각 행의 3번째 값들을 가져옴

[4 8 3]


Row and Column Indexing

In [6]:
print(A[0:2, 1:])

[[2 3 4]
 [5 6 8]]


Fancy Indexing

In [7]:
print(A[[0, 2], [1, 3]]) 
# [0, 2] : 행 / [1, 3] : 열
# 0번째 행의 1열(2), 2번째 행의 3열(3)

[2 3]
