In [1]:
# ! pip install pandas
import pandas as pd
import numpy as np

print(pd.__version__)

2.0.1


In [2]:
## list

a = [1, 2, 3, 4]
a[1:3]

b = [[1, 3, 4],
    [2, 5, 6]]
print(b)

# print([b[0][0], a[0][2]])

c = [10, 'apple', True]
print(c)
np.array(c)

[[1, 3, 4], [2, 5, 6]]
[10, 'apple', True]


array(['10', 'apple', 'True'], dtype='<U11')

In [3]:
# numpy
a = np.array([0, 1, 2, 3, 4])

print('a = ', a)
print(type(a))

a =  [0 1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# numpy
a = np.array([0, 1, 2, 3, 4], dtype= np.int32)

print('a = ', a)
print(type(a))
print(a.dtype)

a =  [0 1 2 3 4]
<class 'numpy.ndarray'>
int32


In [5]:
print(a[2:])

[2 3 4]


attribute

In [6]:
print('shape a =', a.shape)
print('dtype a =', a.dtype)

shape a = (5,)
dtype a = int32


In [7]:
print(range(1, 6))

array = np.array([range(i, i + 2)for i in[1, 4, 7]])    
print(array)

range(1, 6)
[[1 2]
 [4 5]
 [7 8]]


In [8]:
print(array.shape)
print(array.dtype)

(3, 2)
int32


In [9]:
a = np.array([0, 1])
b = np.array([[0, 1]])

print(a.shape)
print(b.shape)

(2,)
(1, 2)


In [10]:
print(np.eye(3, 5))
print()
print(np.identity(3))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(np.identity(3))
print()
print(np.identity(5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.ones((3, 5))*255

array([[255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.]])

In [15]:
print(np.full((5, 4),fill_value=46))
print()
np.full((5, 4), 7)

[[46 46 46 46]
 [46 46 46 46]
 [46 46 46 46]
 [46 46 46 46]
 [46 46 46 46]]



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [16]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [17]:
## range

print(list(range(1, 8, 2)))

print(np.arange(1, 8, 2))

[1, 3, 5, 7]
[1 3 5 7]


In [18]:
A = np.array([[1, 3, 5, 7, 11],[3, 5, 7, 9, 11]], dtype=np.int64)

a1 = np.arange(1, 10, 2)
a2 = np.arange(3, 12, 2)

A = np.array([a1, a2], np.int64)
print(a1)
print(a2)
print(A)
print(A.shape)
print(A.dtype)

[1 3 5 7 9]
[ 3  5  7  9 11]
[[ 1  3  5  7  9]
 [ 3  5  7  9 11]]
(2, 5)
int64


In [19]:
a = np.identity(5, dtype=np.int64)*2
print(a)

print('shape = ',a.shape)
print('dtype = ',a.dtype)

[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
shape =  (5, 5)
dtype =  int64


In [20]:
arr = np.arange(12)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
arr_3by_4 = arr.reshape(3, 4)
print(arr_3by_4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
print(arr_3by_4)
print()
print(list(arr_3by_4.flat))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [23]:
print(arr_3by_4.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [24]:
pro = np.array([[[0], [1], [2]]])
print(pro.shape)
print()
print(pro.reshape(1, 1, 3))
print()
print(pro.reshape(3, 1, 1))

(1, 3, 1)

[[[0 1 2]]]

[[[0]]

 [[1]]

 [[2]]]


In [25]:
print(pro.shape)

print(pro.squeeze())
print()
print(pro.squeeze().shape)
print()
print(pro.squeeze(axis = 0))
print()
print(pro.squeeze(axis = 2))
print()
print(pro.squeeze(axis = 2).shape)

(1, 3, 1)
[0 1 2]

(3,)

[[0]
 [1]
 [2]]

[[0 1 2]]

(1, 3)


In [26]:
a = np.array([1, 2, 3])
b = np.array([3, 5, 1])
c = np.array([1, 2, 1])

print(a, b, c)
np.vstack([a, b, c])

[1 2 3] [3 5 1] [1 2 1]


array([[1, 2, 3],
       [3, 5, 1],
       [1, 2, 1]])

In [27]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])

print(a,'\n')
print(b,'\n')

print('hstack =', np.hstack([a, b]),'\n')
print('vstack =', np.vstack([a, b]))

[[1]
 [2]
 [3]] 

[[2]
 [3]
 [4]] 

hstack = [[1 2]
 [2 3]
 [3 4]] 

vstack = [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [28]:
a = np.arange(1, 6)
b = np.arange(2, 7)

print(a, b, '\n')

print('hstact =', np.hstack([a, b]), '\n')
print('vstact =', np.vstack([a, b]), '\n')
print('column_stack =', np.column_stack([a, b]))

[1 2 3 4 5] [2 3 4 5 6] 

hstact = [1 2 3 4 5 2 3 4 5 6] 

vstact = [[1 2 3 4 5]
 [2 3 4 5 6]] 

column_stack = [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]


In [29]:
a_data = [[1, 2, 3, 4],
          [2, 4, 6, 8]]

b_data = [6, 6, 5, 4]

print(np.vstack([a_data, b_data]).T)

[[1 2 6]
 [2 4 6]
 [3 6 5]
 [4 8 4]]


In [30]:
# Random sampling

# Uniform (균일분포), integer uniform, Gaussian 분포 (정규분포)

# Uniform

np.random.rand(5)

array([0.08079035, 0.71688824, 0.29430464, 0.15567716, 0.83825073])

In [31]:
a = np.random.rand(3, 5)
print(a)

[[0.89539647 0.51534582 0.67215129 0.47904911 0.90398399]
 [0.24293338 0.11684832 0.94035687 0.75295783 0.69627624]
 [0.39134001 0.97754509 0.87483382 0.81430889 0.52775562]]


In [32]:
np.random.randint(1, 10, 10)

array([9, 8, 4, 1, 1, 3, 9, 3, 5, 9])

In [33]:
np.random.randint(1, 10, (3, 2))

array([[2, 9],
       [1, 8],
       [6, 5]])

In [50]:
np.random.randn(100)
np.random.normal(172, 1, (3, 2))

array([[171.20282641, 172.94526359],
       [172.54558002, 171.74916044],
       [173.27843766, 172.13049136]])

In [51]:
np.random.seed(503)
np.random.normal(172, 1, (3, 2))


array([[171.96989384, 171.60281757],
       [173.31554013, 172.47119604],
       [173.26890398, 172.91296131]])

In [54]:
a = np.array([[1, 2], [3, 4]])

print(a)

print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))
print(np.median(a))

[[1 2]
 [3 4]]
2.5
2.5


In [56]:
print(np.var(a))
print(np.std(a))
print(np.min(a))

1.25
1.118033988749895
1
