In [1]:
import tensorflow
tf = tensorflow.keras

# 전치리할 텍스트
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화
result = tf.preprocessing.text.text_to_word_sequence(text)
print('원분 : ',text)
print('토큰화 : ', result)

원분 :  해보지 않으면 해낼 수 없다
토큰화 :  ['해보지', '않으면', '해낼', '수', '없다']


In [2]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
        ]

In [3]:
token = tf.preprocessing.text.Tokenizer()   # 토큰화 함수 지정
token.fit_on_texts(docs)                    # 토큰화 함수에 문장 적용
print('단어 카운트 :', token.word_counts)   # 단어의 빈도수를 계산한 결과 출력

단어 카운트 : OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [4]:
print('문장 카운트 :', token.document_count)

문장 카운트 : 3


In [5]:
print('각 단어가 몇 개의 문장에 포함되어 있는가 :', token.word_docs)

각 단어가 몇 개의 문장에 포함되어 있는가 : defaultdict(<class 'int'>, {'나누어': 1, '먼저': 1, '토큰화합니다': 1, '단어를': 1, '텍스트의': 2, '각': 1, '인식됩니다': 1, '단어로': 1, '토큰화해야': 1, '딥러닝에서': 2, '사용할': 1, '있습니다': 1, '토큰화한': 1, '결과는': 1, '수': 1})


In [6]:
print('각 단어에 매겨진 인덱스 값 :', token.word_index)

각 단어에 매겨진 인덱스 값 : {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


# 2 단어의 원-핫 인코딩

In [7]:
text_2 = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token_2 = tf.preprocessing.text.Tokenizer()
token_2.fit_on_texts([text_2])
token_2.word_index

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}

In [9]:
x = token_2.texts_to_sequences([text_2])
x

[[1, 2, 3, 4, 5, 6]]

In [10]:
word_size = len(token_2.word_index) + 1
x = tf.utils.to_categorical(x, num_classes=word_size)
x

array([[[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]]], dtype=float32)

# 3 단어 임베딩

In [11]:
model = tf.models.Sequential()
model.add(tf.layers.Embedding(16, 4))

# 4 텍스트를 읽고 긍정, 부정 예측하기

In [12]:
import numpy as np
docs_2 = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.',
          '한 번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', 
          '연기가 어색해요', '재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정함
classes = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [13]:
token_3 = tf.preprocessing.text.Tokenizer()
token_3.fit_on_texts(docs_2)
print(token_3.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [15]:
x = token_3.texts_to_sequences(docs_2)
print('리뷰 텍스트, 토큰화 결과 :', x)

리뷰 텍스트, 토큰화 결과 : [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [16]:
padded_x = tf.preprocessing.sequence.pad_sequences(x, 4)
print('패딩 결과 :', padded_x)

패딩 결과 : [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [17]:
word_size = len(token_3.word_index) + 1

In [19]:
model_2 = tf.models.Sequential()
model_2.add(tf.layers.Embedding(word_size, 8, input_length=4))
model_2.add(tf.layers.Flatten())
model_2.add(tf.layers.Dense(1, activation='sigmoid'))
model_2.summary()

model_2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_2.fit(padded_x, classes, epochs=20)
print(model_2.evaluate(padded_x, classes)[1])

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 4, 8)              176       
                                                                 
 flatten_1 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 209
Trainable params: 209
Non-trainable params: 0
_________________________________________________________________


Epoch 1/20
1/1 [==============================] - 0s 474ms/step - loss: 0.7001 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6977 - accuracy: 0.4000
Epoch 3/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6952 - accuracy: 0.4000
Epoch 4/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6928 - accuracy: 0.4000
Epoch 5/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6903 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6879 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6855 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 20ms/step - loss: 0.6831 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6807 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6783 - accuracy: 0.9000
Epoch 11/20
1/1 [===================